### ISSUE TITLE
[sword-parser] invalid structure new psalm book sections

### ISSUE THREAD

**Issue by chriswep** [tyndale/BibleEngine#118]
there is an issue in the ESV/sword parser: the structure gets messed up somehow in psalms whenever a psalm-book starts -you can see the issue e.g. in Psalm 42 and 73. it seems to be related to the top sections in psalms (the five books) - the chapter starts in the middle of verse 1, the (canonical) psalm title is not included in the psalm and the first few verses are not within a paragraph.

reproduction steps: 
- import the ESV strongs module with the current sword importer. 
- => canonical title of psalm 42 is added to the last verse of psalm 41
- => there is no paragraph around first four verses of Psalm 42
- => similar situation in psalm 73 (and probably beginning of psalm books 4 and 5 as well)

**Comment by chriswep** [comment]
@danbenn i looked a bit into this. `swordModule.getXMLforChapter('Psa 41')` on the ESV sword module shows that the start of chapter 42 is included at the end of verse 41.13. I can't write a test case for it, since the ESV module can't be part of the repo, but here is the output for 41.13:

```
    {
      text: '<div type="x-milestone" subType="x-preverse" sID="pv3031"/><lg sID="gen9333"/> <div type="x-milestone" subType="x-preverse" eID="pv3031"/> <l level="1" sID="gen9334"/><note n="r" osisID="Ps.41.13!crossReference.r" osisRef="Ps.41.13" type="crossReference"><reference osisRef="Luke.1.68">Luke 1:68</reference>; [<reference osisRef="Ps.72.18-Ps.72.19">Ps. 72:18, 19</reference>; <reference osisRef="Ps.89.52">89:52</reference>; <reference osisRef="Ps.106.48">106:48</reference>; <reference osisRef="Ps.150.6">150:6</reference>]</note><w lemma="strong:H1288" src="014">Blessed</w> be the <divineName><w lemma="strong:H3068" src="024">Lord</w></divineName>, the <w lemma="strong:H0430" src="034">God</w> of <w lemma="strong:H3478" src="044">Israel</w>,<l eID="gen9334" level="1"/> <l level="2" sID="gen9335"/>from <w lemma="strong:H5769 strong:H9006 strong:H9009" src="054 051 052">everlasting</w> to <w lemma="strong:H5769 strong:H9002 strong:H5704 strong:H9009" src="074 060 064 071">everlasting</w>!<l eID="gen9335" level="2"/> <l level="1" sID="gen9336" type="x-psalm-doxology"/><w lemma="strong:H0543" src="084">Amen</w> and <w lemma="strong:H0543 strong:H9002" src="094 090">Amen</w>.<l eID="gen9336" level="1" type="x-psalm-doxology"/>  <lg eID="gen9333"/> <div eID="gen9302" type="section"/> <chapter eID="gen9301" osisID="Ps.41"/> <div sID="gen9337" type="section"/> <title>Why Are You Cast Down, O My Soul?</title> <title canonical="true" type="psalm">To the <w lemma="strong:H5329 strong:H9005" src="014 011">choirmaster</w>. A <w lemma="strong:H4905" src="024">Maskil</w><note n="1" osisID="Ps.42.1!note.1" osisRef="Ps.42.1" subType="x-musical-term" type="explanation">Probably a musical or liturgical term</note> of <note n="s" osisID="Ps.42.1!crossReference.s" osisRef="Ps.42.1" type="crossReference"><reference osisRef="1Chr.6.33">1 Chr. 6:33</reference>, <reference osisRef="1Chr.6.37">37</reference></note>the <w lemma="strong:H1121!a strong:H9005" src="034 031">Sons</w> of <w lemma="strong:H7141" src="044">Korah</w>.</title> <title canonical="true" type="x-psalm-book">Book Two</title>',
      verse: 13
    }
```

can you look into this? the stuff about the module index is beyond me.

**Comment by DavidIB** [comment]
I've found the prob in the data and fixed it. Next time I create a module it should be correct. I'm aiming to upgrade the morphology soon, so it will be corrected then.

**Comment by danbenn** [comment]
@DavidIB, wonderful! I'll close this issue for now then 👍
