### ISSUE TITLE
Tabs in Word Defs

### ISSUE THREAD

**Issue by DavidIB** [tyndale/BibleEngine#40]
It would be great to have tabs at the bottom of the word def popup: 
• Find = search for all instances of that same word
• More = longer lexical entry for that same word
• Similar = Related words to chose from which would open their own box
• Morph = Morphology of the actual word clicked on

**Comment by danbenn** [comment]
Would especially love to add, "search for all instances of that same word", but can't until the metadata stuff is added

@chriswep , when we talked about this, there was something missing that made it hard / impossible to find all instances of a Strongs word across the text, right?

**Comment by danbenn** [comment]
#148 #144 #145 #146 

Closing in favor of these smaller issues, which are easier to point and estimate
