### ISSUE TITLE
Some new lines missing in OT defs

### ISSUE THREAD

**Issue by DavidIB** [tyndale/BibleEngine#41]
In the BdbMedDef (word def for OT) some of the <BR> codes don't make a new line
Eg H0216: "1) light<br>1a) light of day"
 appears as "1) light1a) light of day"

See screenshot at https://www.dropbox.com/s/1n70llj84sz9gs7/Screenshot_20190316-104113.png?dl=0

**Comment by danbenn** [comment]
this is fixed
