### ISSUE TITLE
Implement v11n rules

### ISSUE THREAD

**Issue by chriswep** [tyndale/BibleEngine#7]
the v11n data of Tyndale should be implemented into BibleEngine so that normalised bible verse number are generated on import

**Comment by chriswep** [comment]
@DavidIB i add some comments and questions from Slack here, maybe you can comment on those and we continue from there:

Going through the dataset there are a lot of questions how to deal with it in detail. From what i understand now:
• for any given reference we would need at minimum the full text and structure of the previous, given and following chapter as an input for the algorithm.
• Then we look if there is a ruleset that machtes our given reference
• then we do all the tests and select the first column where we have a match (what to do if no match?)
• if we match the english column we don't need to do anything
• else we go down "our" column and execute each instruction top to down to convert the reference in our column to the one in the english column

From my first impression, one big issue i see is how to handle subverses correctly. We would need to define rules what to do in the different situations hat may occur.

David you mentioned some time ago that someone started an implementation of this. If yes, we shouldn't start the work from scratch again.

Additionally, looking at e.g. the dataset at "$Exo.37:1-37:29" i think it may be the easiest if you play this out on paper through each step. Maybe also for a few representative / difficult datasets.

**Comment by DavidIB** [comment]
Jamie, who has been working on this with me, has come up with a very useable format which I'll be working on tomorrow (hopefully).
