### ISSUE TITLE
Expo app: error loading books

### ISSUE THREAD

**Issue by gabrieljoelc** [tyndale/BibleEngine#74]
I found this repo by googling

> "expo" bible app

Getting this when scanning the [QR](https://expo.io/@danbenn/step-bible) with the Expo app.

![image](https://user-images.githubusercontent.com/147849/61494752-e29c4e00-a96b-11e9-802b-869d8d1afe68.png)

**Comment by danbenn** [comment]
Hi @gabrieljoelc , thanks for the bug report! Yes, its currently pretty broken, I'm working on fixing this as we speak.

Would love to hear more about what you're looking to build!

**Comment by danbenn** [comment]
@gabrieljoelc , just fixed the Android build. It should work now. Working on fixing the iOS build
