### ISSUE TITLE
General search architecture for STEP

### ISSUE THREAD

**Issue by dakrone** [tyndale/BibleEngine#92]
# Table of Contents

1.  [A general search architecture for STEP](#org07ebfc6)
2.  [An argument for separating search implementation from its consumer](#org4667aa7)
3.  [Use cases](#org83dd5e2)
    1.  [Phrase based searching](#org1370200)
    2.  [Stemming](#orgdc060ac)
    3.  [Fuzzy matching](#orgeb43ce5)
    4.  [Stop words](#orgb834743)
    5.  [Ranking customization](#org5a16085)
        1.  [Ranking algorithm customization](#org3895187)
        2.  [Ranking customization through query design](#org11a65d1)
    6.  [Per-language analysis](#org80ed27e)
    7.  [Aggregations/Facets](#org0fbdaa8)
    8.  [Query capture](#org5fa72d1)
4.  [General observations](#orgbd87399)

<a id="org07ebfc6"></a>

# A general search architecture for STEP

This issue describes some of the strengths and shortcomings of the current STEP bible search functionality.

I'm by no means an expert in biblical languages, and while there is a lot that can be done with these, I'll **mostly** focus on English searching to make it approachable for anyone.

A quick note about search technology and my personal bias - I'm an [Elasticsearch](https://github.com/elastic/elasticsearch/) developer, and since its the search technology I'm the most familiar and comfortable with, I'm slightly biased by my recommendation of it. My hope is that this is general enough to apply to any search solution, regardless of whether Elasticsearch, or a different search implementation is used.

I'd also like to note that the existing search infrastructure is really cool! Part of what drew me to stepbible was its ability to link Greek/Hebrew words across to the English equivalent in a manner perfect for bible studies. Awesome job for the existing search infrastructure!

<a id="org4667aa7"></a>

# An argument for separating search implementation from its consumer

From an architectural perspective, I think it's better to separate the implementation of the search from the consumer implementations. The benefits of separating search from the consumer are:

-   Separating search means code doesn't have to be duplicated if additional projects want to add search. Imagine if a mobile application and a web application both wanted search, it makes more sense for the search to be accessible and **common** across either for an equivalent search user experience.
-   Search implementation can be language-agnostic for consumers. The mobile app may be in Javascript, the website may be in Java, or PHP, or XYZ. Separating search implementation behind a REST API means any subsequent projects aren't limited to languages that the search implementation supports (for example, Lucene only supporting JVM languages)
-   Deployment and management ease. If a change requires a newer version of Lucene or other search library, there's no need to deploy an entirely new web/mobile application.

<a id="org83dd5e2"></a>

# Use cases

These are some various use cases I think it would be beneficial to support. It's by no means exhaustive as Information Retrieval<sup><a id="fnr.1" class="footref" href="#fn.1">1</a></sup> is a huge subject, these are some of the more important ones that occurred to me.

<a id="org1370200"></a>

## Phrase based searching

Currently when searching STEPBible for a phrase, it appears that the query terms are treated separately, for example, compare the output of a query for "for god so loved the world":

<https://www.stepbible.org/?q=text=for%20god%20so%20loved%20the%20world&options=VHRNGUC>

Which treats each term separately, returning almost every verse in the bible that contains the word "the", instead of what we'd expect (John 3:16)

With:

<https://www.biblegateway.com/quicksearch/?quicksearch=for+god+so+loved+the+world&qs_version=ESV>

Which returns the verse a user is probably searching for (John 3:16)

Bible Gateway also supports ****slop**** (a variant of fuzzy matching that applies to phrase queries), where a [search missing the word loved](https://www.biblegateway.com/quicksearch/?quicksearch=for+god+so+the+world&qs_version=ESV) still finds the verse.

<a id="orgdc060ac"></a>

## Stemming

Stemming is the act of reducing a word to its base in order to match all variants of a word, for example, the words "cactus" and "cacti" are both stemmed to the base "cact" so that a search for either of them returns the other.

An example with the existing search, take this query for the word "preach":

<https://www.stepbible.org/?q=version=ESV|reference=1Cor.9|text=preach&options=VHRNGUC>

and this query for the word "preaching":

<https://www.stepbible.org/?q=version=ESV|reference=1Cor.9|text=preaching&options=VHRNGUC>

Each of these queries returns different results, but a user may not remember if the verse they are looking for contained "preach" or "preaching".

This is a common analysis step in Information Retrieval systems.

<a id="orgeb43ce5"></a>

## Fuzzy matching

Fuzzy matching is the ability to match phrases that may be misspelled, for example, if someone misspells the word "struggle" as "struglle", searching with fuzzy matching allows documents to match regardless. This is especially useful for mobile applications where spelling may not always be correct :)

Fuzziness in IR<sup><a id="fnr.2" class="footref" href="#fn.2">2</a></sup> systems is usually based on [Levenshtein Distance](https://en.wikipedia.org/wiki/Levenshtein_distance) between two strings.

It appears SB doesn't currently support this, as a query for "preech" returns no results:

<https://www.stepbible.org/?q=version=ESV|reference=1Cor.9|text=preech&options=VHRNGUC>

<a id="orgb834743"></a>

## Stop words

I noticed that STEP doesn't current elide stopwords, a query for any phrase with the word "the" matches the majority of the languages. In some cases keeping stop words is desirable, for example, with exact phrase matches, but when searching for a loose collection of terms, stop words generally are not useful and only detract from better retrieval.

<https://www.stepbible.org/?q=version=ESV|reference=1Cor.9|text=the%20word&options=VHRNGUC>

An example (from Lucene) of the default stopwords to be filtered out (though it is completely customizable):

"a", "an", "and", "are", "as", "at", "be", "but", "by", "for", "if", "in", "into", "is", "it", "no", "not", "of", "on", "or", "such", "that", "the", "their", "then", "there", "these", "they", "this", "to", "was", "will", "with"

Scoring algorithms should also take this into account for scoring (later versions of Lucene do this better) so that a query like this won't have results matching just the word "the" scored at the top of the results.

<a id="org5a16085"></a>

## Ranking customization

There are two parts of ranking that should be considered:

<a id="org3895187"></a>

### Ranking algorithm customization

It appears that JSword (and by extension stepbible) uses Lucene 2.3<sup><a id="fnr.3" class="footref" href="#fn.3">3</a></sup>, which uses [TF-IDF](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) for its retrieval scoring algorithm (unless they changed the default, I didn't check but its unlikely).

I would recommend switching to something using [BM25](https://en.wikipedia.org/wiki/Okapi_BM25) or BM25f (If you want to geek out over the math, check out [this great talk](https://www.youtube.com/watch?v=v3Ko0CwgTZ0) by a coworker of mine) as it specifically handles small documents better, and in the world of biblical text indexing, a document usually ends up being a single verse (small).

Switching to BM25 also allows tailoring the `b` and `k` to get better scoring between longer and shorter verses.

It may also be possible to use [Word2vec](https://en.wikipedia.org/wiki/Word2vec) for scoring, though this is much more complex and would require a lot more work.

Eventually, it's also nice to add POS-tagging (Parts Of Speech Tagging) into relevance calculations to rank differently grammar higher or lower.

<a id="org11a65d1"></a>

### Ranking customization through query design

The other part of ranking is combining queries in such a way that you score a document based on different (but not mutually exclusive) criteria.

Take for example a query "preaching the word".

A run down of an example of the way I would generate a query for this would be, in order of highest scoring to lowest scoring:

-   A query for the exact phrase "preaching the word"
-   A query for the phrase "preaching the word" but using stemming so it matched "preached the word" or "preach the word"
-   A query discarding stopwords so "preaching the word" also matches "preaching a word"
-   A query treating each term individually, so a verse with "preach" and "word" would match

These multiple queries cascade in terms of the influence over the score and can have tweakable weights to change how much influence over the score each one has.

There's no current example of this for stepbible as it appears not to support stemming or phrase queries, but you can see sort of an example at <https://www.biblegateway.com/quicksearch/?quicksearch=preaching+the+word&qs_version=ESV>

<a id="org80ed27e"></a>

## Per-language analysis

I recall seeing a declaration for the intention to add multi-lingual support to stepbible, that's great!

One thing to be aware of is the different challenges different languages pose to IR systems, rather than this being an afterthought, any search system should support different language analyzers as part of its indexing and querying pipeline (Lucene and any Lucene-based system has this covered very well).

It's also possible to do phonetic or morphological analysis on words, which could be very neat.

Another useful thing would be normalization, which changes something like `Ü` into `U` because, let's be honest, not that many native English speakers know how to type accented characters correctly :)

<a id="org0fbdaa8"></a>

## Aggregations/Facets

Something that Stepbible currently only does a very little of is aggregating or faceting on data provided. An example of this is in Stepbible is the "sort by frequency" for the text that sorts terms based on their frequency.

Aggregations allow us to gather information in the following format

"What are the top 20 most common words occurring in each book book of the bible with a minimum occurrence count of 5?"

or

"What is the average number of times the word θεός occurs in each book of the New Testament?"

This faceting can also help when presenting a search results screen to a user, allowing a user to add filters to their existing query by selection a aggregated value (for example, think of an e-commerce site that shows products from different categories), or it can be helpful for a scholar doing a study on the frequencies and occurrences of words (I think Logos does something like this if I am not mistaken).

<a id="org5fa72d1"></a>

## Query capture

An information retrieval system is only as good as its feedback loop. What difference does it make if you **think** you're improving search for your users, but you never measure it? There are a few things that IR systems should do to help:

-   Capture every query that goes through the system
-   Have a user feedback loop - this could be as simple as a "find what you're looking for? yes/no" that links a user's experience to a query that can be checked to see if there is a way to improve the search system. If you don't have feedback, how do you know if a user is satisfied by the search system?
-   Have a "control" corpus of example queries and their expected matches - for example, I expected "for god so loved the world" to match John 3:16 above. Having something like this allows you to make changes and retest with your existing control corpus to ensure you didn't accidentally break anything with any further changes made
-   Add the ability to a/b between different analysis options - it's great to be able to test something with either version and see whether

<a id="orgbd87399"></a>

# General observations

As I mentioned above, IR can be very complex and the hardest part of building a good search is hiding the complexity while also giving the necessary power to the user. Depending on the user, they may want to tweak certain things, or not even know about them. Tailoring a search usually entails asking questions about the users of a particular piece of software, feedback is crucial for steering a project away from needless complexity.

# Footnotes

<sup><a id="fn.1" href="#fnr.1">1</a></sup> <https://en.wikipedia.org/wiki/Information_retrieval>

<sup><a id="fn.2" href="#fnr.2">2</a></sup> Information Retrieval

<sup><a id="fn.3" href="#fnr.3">3</a></sup> Wow. That is a very old version of Lucene.

**Comment by danbenn** [comment]
These comments are really helpful, and will inform how a future search engine will be built for STEP. 

I moved this to the wiki, and am closing this issue for now, just so that issues can just be for bugs and user stories:
https://github.com/tyndale/BibleEngine/wiki/A-General-Search-Architecture-for-STEP

Thanks again, @dakrone !
